networks:
  iot_net:
    driver: bridge

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_broker
    ports:
      - "8883:8883"                                                    # MQTT seguro (TLS)
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/passwordfile:/mosquitto/config/passwordfile        # usuarios (1.1)
      - ./mosquitto/aclfile:/mosquitto/config/aclfile                  # permisos por topico (1.4)
      - ./mosquitto/certs:/mosquitto/config/certs                      # CA + cert servidor (1.2)
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - iot_net
    restart: unless-stopped

  nodered:
    image: nodered/node-red:latest-debian
    container_name: nodered_app
    ports:
      - "1880:1880"
    volumes:
      # guarda flujos, configuraciones y nodos descargados para evitar perdida de datos
      - ./nodered_data:/data
      # directorio mapeado para guardar temporalmente las capturas del esp32-cam
      - ./imagenes_camara:/tmp/imagenes
      
    networks:
      - iot_net
    restart: unless-stopped
    depends_on:
      - mosquitto

  reconocimiento_facial:
    build: ./servicio_reconocimiento
    container_name: iot_reconocimiento
    ports:
      - "5000:5000"
    volumes:
      - ./imagenes_camara:/tmp/imagenes
      - ./servicio_reconocimiento/caras_conocidas:/app/caras_conocidas
    networks:
      - iot_net
    restart: unless-stopped