# persistencia y logs
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

# sin acceso anonimo
allow_anonymous false
password_file /mosquitto/config/passwordfile

# control de acceso por topico
acl_file /mosquitto/config/aclfile

# cifrado tls
listener 8883
cafile   /mosquitto/config/certs/ca.crt
certfile /mosquitto/config/certs/server.crt
keyfile  /mosquitto/config/certs/server.key

tls_version tlsv1.2

# no presentan certificado propio los dispositivos que se conecten
require_certificate false


